language: ruby
cache: bundler
bundler_args: --without yard pry
sudo: false
rvm:
  - 2.2.7
  - 2.3.4
  - 2.4.1
  - jruby-9.1.8.0
  - ruby-head
  - jruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
  fast_finish: true
